### ISSUE TITLE
Liquid tag error build

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#50]
Hello, 

I did the local build and it works but once I put it on gh-pages I get this tag error, why is this happening?

 Your site is having problems building: The tag podigee_player on line 1 in _posts/2016-03-22-episode0.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

**Comment by haslinger** [comment]
This is happening, because github pages does only support [this list of gems](https://pages.github.com/versions/) directly.

So you can't use github pages to let them build the page.
You can build locally, push that generated code to a DIFFERENT repo and use that for a site.
We do this with [the source](https://github.com/jekyll-octopod/jekyll-octopod.github.io.source) for the demo site and the [project site](https://github.com/jekyll-octopod/jekyll-octopod.github.io).
