### ISSUE TITLE
playing audio

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#52]
Hello, 

I was just trying to play the included episode and the audio file but it doesnt find the source, is this suppose to work out of the box?

https://rafael-git.github.io/2016/03/22/episode0.html#6dc82a9e

**Comment by haslinger** [comment]
No. That's why we put in page 3 of the documentation: [Configuration](https://jekyll-octopod.github.io/configuration)
You are expected to set the config settings in the _config file, especially the ones denoted with 
`# You should configure this`
In your particular case, you didn't update the setting `download url`. It is still set to:
`download_url: "http://your.fancy.hosting/episodes"`
