### ISSUE TITLE
Octopod incompatible with Ruby 2.6.0

### ISSUE THREAD

**Issue by chetwisniewski** [jekyll-octopod/jekyll-octopod#59]
Running Arch Linux, jekyll seems to be OK with latest ruby (2.6.2-1), but octopod throws errors and doesn't embed content correctly. Log of errors attached as well as a screenshot of the non-rendered page.
![Screenshot from 2019-03-17 11-18-13](https://user-images.githubusercontent.com/1812967/54497680-eedba600-48ba-11e9-847d-091942058075.png)
[Octopod-error-ruby2.6.2.log](https://github.com/jekyll-octopod/jekyll-octopod/files/2975678/Octopod-error-ruby2.6.2.log)

**Comment by haslinger** [comment]
I am running old and fresh instances of jekyll-octopod with ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux] without any issues.
There are some aspects interesting about your report:
* There is no ruby 2.6.2-1, at least this not standard ruby versioning scheme
* Your screenshot contains paths with .../ruby/2.6.0/.... Seems there is a mixture of different ruby installations on your system.
I have personally seen weird things happening when using system ruby (ruby, that comes with via the packaging system of the distro). That's why I'm using rvm for 8 years now.

**Comment by chetwisniewski** [comment]
The screenshot was from a month ago so the version mismatch is from then to current. The -1 is just Arch versioning. Will explore rvm. Using system ruby 2.4 made it work, so there is certainly something about 2.6 causing those errors, but I guess it could just be for the Arch version of ruby.

**Comment by chetwisniewski** [comment]
My apologies. A fresh ruby install resolved the issue. Must have been some legacy settings somewhere from another app.
