### ISSUE TITLE
Subtitle field adding "-$subtitle" to episode titles in RSS

### ISSUE THREAD

**Issue by skoobasteeve** [jekyll-octopod/jekyll-octopod#71]
I'm trying to figure out what the expected behavior of the Subtitle field is in episode posts. Currently, if I add a subtitle, it adds it onto the episode title in by adding a hyphen and then the subtitle (Title - $subtitle). I would prefer this not to happen since Apple Podcasts shows it as a duplicate (see attached screenshot). If I choose to not add a subtitle, the hyphen is still added at the end of the title (see attached screenshot). 

How can I avoid this behavior? Do you have an example episode template where this behavior doesn't occur? 

Site is https://pod.raylyon.info

Thank you!

![gpodder](https://user-images.githubusercontent.com/36998292/80255875-c987a280-864b-11ea-8ded-f6697caca480.png)

<img width="446" alt="Screen Shot 2020-04-24 at 4 42 55 PM" src="https://user-images.githubusercontent.com/36998292/80255973-f340c980-864b-11ea-808e-203997672f42.png">

**Comment by haslinger** [comment]
There is no expected behavior, just a default behavior. That is why all assets are copied into the app directory. Change them to your needs, the feed template is in `_layouts/feed.xml`, the post title of an episode within the website in `_includes/post_header.html`, just to give two examples.
Basically just look around in the _includes and the _layouts directory and modify to your needs.

I don't provide any other templates than the one shipped in the gem copied into the project, I expect the gem's users to have basic knowledge of Jekyll and Liquid and I'm not able to provide customizing support for individual uses of the gem, sorry.

**Comment by skoobasteeve** [comment]
Thank you for the reply! I'll dig into this on my own. Know a little Jekyll and HTML but learning as I go.

**Comment by haslinger** [comment]
I would further recommend you reading about Liquid, the templating language used by Jekyll: 
https://shopify.github.io/liquid/ 
I first expected Liquid to contain any Ruby I like, but that's totally not the case.
Understanding Liquid will demystify most of Jekyll for you.
